name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Install dependencies
      run: make deps
      
    - name: Checking formatting and linting code
      run: make check

    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        install-go: false

    - name: Build for all supported platforms
      run: make buildall
      
    - name: Run unit-tests
      run: make test
