name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: make deps
      
    - name: Build for all supported platforms
      run: make buildall
      
    - name: Run unit-tests
      run: make test
      
#TODO: Add a make target to check formatting and staticcheck
