name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: make deps
      
    - name: Checking formatting and linting code
      run: make check

    - name: Build for all supported platforms
      run: make buildall
      
    - name: Run unit-tests
      run: make test
